### ISSUE TITLE
Slicing

### ISSUE THREAD

**Issue by eulere28** [eulere28/single-cycle-cpu#3]
Slicing Problem in ImmGen File Line 16.
https://github.com/eulere28/single-cycle-cpu/blob/main/lib/ImmGen.dart

**Comment by quekyj** [comment]
Your output is width of 32 `final immOut = addOutput('immOut', width: 32);` but you assign width 12 to it `instCode.slice(31, 20)`. I am not sure if this is the error your encounter? Its good if you can provide more details on your problem.
